### ISSUE TITLE
コメントに関して

### ISSUE THREAD

**Issue by S901059999** [stratosphere2018/quadrone#10]
本当にこんな**無意味なコメント**をやめておこう：
```
/// <summary>
/// バトルフィールド
/// </summary>
public class Field : MonoBehaviour
```

もし他のフィールドがあるか？
じゃ最初名前をBattleFieldに付けてください。
ほぼ全部コメントは同じの問題だから、残りのは略。

しばらく記録したいと、初心者の教える以外、
**コメントは英語だけを勧める。**
まずは、英語はプログラマーの共通言語、今の開発環境はとても国際化だから、
日本人のためのコメントをしないでください。
また、英語以外の文字を使ったら、いろいろな意外を発生する可能性がある。
たとえ今は全然影響がなくても、プロジェクトの安定性を重視するになろう。

**Comment by o0-kettle-0o** [comment]
うん、正直に言って暇つぶしと自己満足以外の何物でもなかった。

```Unity
/// <summary>
/// バトルフィールド
/// </summary>
public class Field : MonoBehaviour
```

上記のコメントは
_`Field`にマウスオーバーしたときになにも書かれてないのが寂しい_
ってだけの理由で書いたコメントなので**本当に無意味**です。
後で消しとくね

**Comment by S901059999** [comment]
寂しいはわかるけど、
**何も書いていないこそ良いコードの証明だ**。

無意味なコメントはただコードを見るの時間を増やさせる、
それは本当によくない。
**実際にコードを書くとき、見るの時間は書くのより長い**。
そして見なくていいじゃないか？
いや、コードの行数が多くなる時に、みたいコードを探す時間も増やした。
ページのスクロールも時間をかかるよ。
従って、無意味なコメントは**コード書くを妨害するの行為**だ。
