### ISSUE TITLE
stringタイプの名前を構造で管理する

### ISSUE THREAD

**Issue by S901059999** [stratosphere2018/quadrone#11]
1. Scene
2. Input Axes

enum、struct、classなどを使て、
stringを一ヶ所に集中する。
stringの内容を変更したいときは**そこだけ変えていい**。

もちろん、**意外なパラメータが防げる**の利点もある。

**Comment by o0-kettle-0o** [comment]
目から鱗
その中ならとりあえずenumかな

**Comment by o0-kettle-0o** [comment]
ちょっと迂遠な方法だけど一応解決したので閉じます
