### ISSUE TITLE
Unityのバージョンを勝手に更新しないでください

### ISSUE THREAD

**Issue by S901059999** [stratosphere2018/quadrone#12]
もし更新の必要があれば、
少なくともチーム全員に**更新の理由**を知らせてください。
これもメインプログラマー全員議論をした後で執行するべきの重大事項。

まずは更新は時間を費やす、その後もプロジェクトが壊れて修正し必要の可能性が出る。

**Comment by o0-kettle-0o** [comment]
以後気を付けます。

今回の更新の理由はプロジェクトが開始していなかったため、でしょうか
